package com.pokergame.gui;

import com.pokergame.backend.IOHelper;
import com.pokergame.backend.Player;
import com.pokergame.gui.MainGUI;
import com.pokergame.gui.RegisterGUI;
import java.awt.Color;
import java.awt.Font;
import java.util.HashMap;

/**
 *
 * @author riana joy
 */
public class LauncherGUI extends javax.swing.JFrame {

    /**
     * Creates new form Launcher
     */
    public LauncherGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LauncherPanel = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        UsernameInvalidLabel = new javax.swing.JLabel();
        PasswordIncorrectLabel = new javax.swing.JLabel();
        RegisterB = new javax.swing.JButton();
        LoginB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Launcher");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setForeground(new java.awt.Color(51, 51, 51));
        setName("LauncherGUI"); // NOI18N
        setResizable(false);

        UsernameLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        UsernameLabel.setText("Username: ");

        PasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        PasswordLabel.setText("Password: ");

        UsernameField.setCaretColor(new java.awt.Color(204, 204, 204));

        PasswordField.setCaretColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout LauncherPanelLayout = new javax.swing.GroupLayout(LauncherPanel);
        LauncherPanel.setLayout(LauncherPanelLayout);
        LauncherPanelLayout.setHorizontalGroup(
            LauncherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LauncherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LauncherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LauncherPanelLayout.createSequentialGroup()
                        .addGroup(LauncherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LauncherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(UsernameField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LauncherPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(LauncherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameInvalidLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordIncorrectLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        LauncherPanelLayout.setVerticalGroup(
            LauncherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LauncherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LauncherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameInvalidLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LauncherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordIncorrectLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RegisterB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RegisterB.setText("Register");
        RegisterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBActionPerformed(evt);
            }
        });

        LoginB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LoginB.setText("Log In");
        LoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LauncherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LoginB, RegisterB});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LauncherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginB)
                    .addComponent(RegisterB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBActionPerformed
        this.dispose();
        new RegisterGUI().setVisible(true);
    }//GEN-LAST:event_RegisterBActionPerformed

    private void LoginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBActionPerformed
        resetState();
        HashMap<String, Player> players = IOHelper.deserialize();
        boolean errorDetected = false;
        String username = UsernameField.getText();
        String password = new String(PasswordField.getPassword());
        if (username.equals("") || !players.containsKey(username)) {
            UsernameInvalidLabel.setText("Input a valid username!");
            UsernameInvalidLabel.setForeground(Color.RED);
            UsernameInvalidLabel.setFont(new Font("Tahoma", Font.BOLD, 10));
            errorDetected = true;
            this.setSize(305, 170);
            return;
        }
        Player player;
        player = players.get(username);

        if (password.equals("") || !password.equals(player.getPassword())) {
            PasswordIncorrectLabel.setText("Password incorrect!");
            PasswordIncorrectLabel.setForeground(Color.RED);
            PasswordIncorrectLabel.setFont(new Font("Tahoma", Font.BOLD, 10));
            errorDetected = true;
            this.setSize(305, 170);
            return;
        }

        this.dispose();
        MainGUI game = new MainGUI();
        game.setPlayingPlayer(player);
        game.setVisible(true);

    }//GEN-LAST:event_LoginBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LauncherGUI().setVisible(true);
            }
        });
    }

    public void resetState() {
        UsernameInvalidLabel.setText("");
        PasswordIncorrectLabel.setText("");
        this.setSize(305, 156);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LauncherPanel;
    private javax.swing.JButton LoginB;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordIncorrectLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton RegisterB;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameInvalidLabel;
    private javax.swing.JLabel UsernameLabel;
    // End of variables declaration//GEN-END:variables
}
