package com.pokergame.gui;

import com.pokergame.backend.IOHelper;
import com.pokergame.backend.Player;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author riana joy
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form GameGUI
     */
    public MainGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        setHighScores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new com.pokergame.gui.MainPanel();
        StartupPanel = new javax.swing.JPanel();
        StartGameB = new javax.swing.JButton();
        PokerTitle = new javax.swing.JLabel();
        HighScoresB = new javax.swing.JButton();
        HelpB = new javax.swing.JButton();
        LogoutB = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();
        CashLabel = new javax.swing.JLabel();
        HelpPanel = new javax.swing.JPanel();
        woodPanel2 = new com.pokergame.gui.WoodPanel();
        tablePanel1 = new com.pokergame.gui.TablePanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        MenuB = new javax.swing.JButton();
        HighScorePanel = new javax.swing.JPanel();
        woodPanel1 = new com.pokergame.gui.WoodPanel();
        tablePanel2 = new com.pokergame.gui.TablePanel();
        highscoreTitle = new javax.swing.JLabel();
        usernameTitleLabel = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        username4 = new javax.swing.JLabel();
        username5 = new javax.swing.JLabel();
        username6 = new javax.swing.JLabel();
        username7 = new javax.swing.JLabel();
        username8 = new javax.swing.JLabel();
        username9 = new javax.swing.JLabel();
        scoreTitleLabel = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        score3 = new javax.swing.JLabel();
        score4 = new javax.swing.JLabel();
        score5 = new javax.swing.JLabel();
        score6 = new javax.swing.JLabel();
        score7 = new javax.swing.JLabel();
        score8 = new javax.swing.JLabel();
        score9 = new javax.swing.JLabel();
        MenuFrmHighScoreB = new javax.swing.JButton();
        username10 = new javax.swing.JLabel();
        score10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Poker 1.0");
        setFocusCycleRoot(false);
        setName("gameFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        mainPanel1.setPreferredSize(new java.awt.Dimension(600, 550));
        mainPanel1.setLayout(new java.awt.CardLayout());

        StartupPanel.setOpaque(false);
        StartupPanel.setPreferredSize(new java.awt.Dimension(600, 550));

        StartGameB.setBackground(new java.awt.Color(204, 204, 204));
        StartGameB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StartGameB.setText("Start Game");
        StartGameB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameBActionPerformed(evt);
            }
        });

        PokerTitle.setFont(new java.awt.Font("Times New Roman", 0, 80)); // NOI18N
        PokerTitle.setForeground(new java.awt.Color(255, 255, 255));
        PokerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PokerTitle.setText("POKER");

        HighScoresB.setBackground(new java.awt.Color(204, 204, 204));
        HighScoresB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HighScoresB.setText("High Scores");
        HighScoresB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighScoresBActionPerformed(evt);
            }
        });

        HelpB.setBackground(new java.awt.Color(204, 204, 204));
        HelpB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HelpB.setText("Help");
        HelpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpBActionPerformed(evt);
            }
        });

        LogoutB.setBackground(new java.awt.Color(204, 204, 204));
        LogoutB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LogoutB.setText("Log Out");
        LogoutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBActionPerformed(evt);
            }
        });

        WelcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setText("Welcome Label");

        CashLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        CashLabel.setForeground(new java.awt.Color(255, 255, 255));
        CashLabel.setText("Cash label");

        javax.swing.GroupLayout StartupPanelLayout = new javax.swing.GroupLayout(StartupPanel);
        StartupPanel.setLayout(StartupPanelLayout);
        StartupPanelLayout.setHorizontalGroup(
            StartupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartupPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(StartupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PokerTitle)
                    .addComponent(CashLabel)
                    .addComponent(WelcomeLabel)
                    .addGroup(StartupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(StartGameB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HelpB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoutB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HighScoresB)))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        StartupPanelLayout.setVerticalGroup(
            StartupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartupPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(PokerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(WelcomeLabel)
                .addGap(15, 15, 15)
                .addComponent(CashLabel)
                .addGap(32, 32, 32)
                .addComponent(StartGameB)
                .addGap(20, 20, 20)
                .addComponent(HighScoresB)
                .addGap(20, 20, 20)
                .addComponent(HelpB)
                .addGap(20, 20, 20)
                .addComponent(LogoutB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel1.add(StartupPanel, "StartCard");

        HelpPanel.setPreferredSize(new java.awt.Dimension(600, 550));

        tablePanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        tablePanel1.setPreferredSize(new java.awt.Dimension(600, 518));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("HOW TO PLAY POKER: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("1. The game starts by placing your bet.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("2. Click the \"Draw\" button to draw 5 cards from a randomly-shuffled deck.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("3. Flip over the cards you want to remove from your hand.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("4. Click the \"Change\" button to replace the flipped cards for new ones.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("5. Click the \"Deal\" button to play the cards.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("6. Payout is as follows:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Royal Flush - 8x");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Baby Flush - 6x");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Straight Flush - 5x");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Quads - 4x");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Full House -2.5x");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Flush - 2x");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Straight - 1.75x");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Triples - 1.5x");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("2 Pairs - 1.25x");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Pair - 1x");

        MenuB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MenuB.setText("Menu");
        MenuB.setContentAreaFilled(false);
        MenuB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuBMouseExited(evt);
            }
        });
        MenuB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MenuBMouseDragged(evt);
            }
        });
        MenuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablePanel1Layout = new javax.swing.GroupLayout(tablePanel1);
        tablePanel1.setLayout(tablePanel1Layout);
        tablePanel1Layout.setHorizontalGroup(
            tablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanel1Layout.createSequentialGroup()
                .addGroup(tablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(tablePanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(tablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(31, 31, 31)
                        .addGroup(tablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)))
                    .addComponent(jLabel18))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MenuB)
                .addGap(60, 60, 60))
        );
        tablePanel1Layout.setVerticalGroup(
            tablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addGap(8, 8, 8)
                .addGroup(tablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(MenuB)
                .addContainerGap())
        );

        javax.swing.GroupLayout woodPanel2Layout = new javax.swing.GroupLayout(woodPanel2);
        woodPanel2.setLayout(woodPanel2Layout);
        woodPanel2Layout.setHorizontalGroup(
            woodPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(woodPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(tablePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        woodPanel2Layout.setVerticalGroup(
            woodPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, woodPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(tablePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HelpPanelLayout = new javax.swing.GroupLayout(HelpPanel);
        HelpPanel.setLayout(HelpPanelLayout);
        HelpPanelLayout.setHorizontalGroup(
            HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(woodPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HelpPanelLayout.setVerticalGroup(
            HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(woodPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel1.add(HelpPanel, "HelpCard");

        woodPanel1.setPreferredSize(new java.awt.Dimension(600, 550));

        tablePanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        highscoreTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        highscoreTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscoreTitle.setText("HIGH SCORES");

        usernameTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernameTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameTitleLabel.setText("Username");

        username1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("none");

        username2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username2.setText("none");

        username3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username3.setText("none");

        username4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username4.setText("none");

        username5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username5.setText("none");

        username6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username6.setText("none");

        username7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username7.setText("none");

        username8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username8.setText("none");

        username9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username9.setText("none");

        scoreTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scoreTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreTitleLabel.setText("Score");

        score1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score1.setText("N/A");

        score2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score2.setText("N/A");

        score3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score3.setText("N/A");

        score4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score4.setText("N/A");

        score5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score5.setText("N/A");

        score6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score6.setText("N/A");

        score7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score7.setText("N/A");

        score8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score8.setText("N/A");

        score9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score9.setText("N/A");

        MenuFrmHighScoreB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuFrmHighScoreB.setText("Menu");
        MenuFrmHighScoreB.setBorderPainted(false);
        MenuFrmHighScoreB.setContentAreaFilled(false);
        MenuFrmHighScoreB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuFrmHighScoreBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuFrmHighScoreBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuFrmHighScoreBMouseExited(evt);
            }
        });
        MenuFrmHighScoreB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFrmHighScoreBActionPerformed(evt);
            }
        });

        username10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username10.setText("none");

        score10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score10.setText("N/A");

        javax.swing.GroupLayout tablePanel2Layout = new javax.swing.GroupLayout(tablePanel2);
        tablePanel2.setLayout(tablePanel2Layout);
        tablePanel2Layout.setHorizontalGroup(
            tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablePanel2Layout.createSequentialGroup()
                        .addComponent(username10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score10))
                    .addGroup(tablePanel2Layout.createSequentialGroup()
                        .addComponent(username1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score1))
                    .addGroup(tablePanel2Layout.createSequentialGroup()
                        .addComponent(usernameTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scoreTitleLabel))
                    .addGroup(tablePanel2Layout.createSequentialGroup()
                        .addComponent(username9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score9))
                    .addGroup(tablePanel2Layout.createSequentialGroup()
                        .addComponent(username2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score2))
                    .addGroup(tablePanel2Layout.createSequentialGroup()
                        .addComponent(username3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score3))
                    .addGroup(tablePanel2Layout.createSequentialGroup()
                        .addComponent(username4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score4))
                    .addGroup(tablePanel2Layout.createSequentialGroup()
                        .addComponent(username5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score5))
                    .addGroup(tablePanel2Layout.createSequentialGroup()
                        .addComponent(username6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score6))
                    .addGroup(tablePanel2Layout.createSequentialGroup()
                        .addComponent(username7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score7))
                    .addGroup(tablePanel2Layout.createSequentialGroup()
                        .addComponent(username8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanel2Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(highscoreTitle)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(tablePanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MenuFrmHighScoreB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tablePanel2Layout.setVerticalGroup(
            tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(highscoreTitle)
                .addGap(30, 30, 30)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTitleLabel)
                    .addComponent(scoreTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username1)
                    .addComponent(score1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username2)
                    .addComponent(score2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username3)
                    .addComponent(score3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username4)
                    .addComponent(score4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username5)
                    .addComponent(score5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username6)
                    .addComponent(score6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username7)
                    .addComponent(score7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username8)
                    .addComponent(score8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username9)
                    .addComponent(score9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username10)
                    .addComponent(score10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuFrmHighScoreB)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout woodPanel1Layout = new javax.swing.GroupLayout(woodPanel1);
        woodPanel1.setLayout(woodPanel1Layout);
        woodPanel1Layout.setHorizontalGroup(
            woodPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, woodPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(tablePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        woodPanel1Layout.setVerticalGroup(
            woodPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, woodPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(tablePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HighScorePanelLayout = new javax.swing.GroupLayout(HighScorePanel);
        HighScorePanel.setLayout(HighScorePanelLayout);
        HighScorePanelLayout.setHorizontalGroup(
            HighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HighScorePanelLayout.createSequentialGroup()
                .addComponent(woodPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        HighScorePanelLayout.setVerticalGroup(
            HighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HighScorePanelLayout.createSequentialGroup()
                .addComponent(woodPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel1.add(HighScorePanel, "HighScoreCard");

        getContentPane().add(mainPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartGameBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameBActionPerformed
        this.dispose();
        GameGUI game = new GameGUI();
        game.setPlayingPlayer(player);
        game.setVisible(true);

    }//GEN-LAST:event_StartGameBActionPerformed

    private void HighScoresBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighScoresBActionPerformed

        CardLayout card = (CardLayout) mainPanel1.getLayout();
        card.show(mainPanel1, "HighScoreCard");
    }//GEN-LAST:event_HighScoresBActionPerformed

    private void HelpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpBActionPerformed

        CardLayout card = (CardLayout) mainPanel1.getLayout();
        card.show(mainPanel1, "HelpCard");
    }//GEN-LAST:event_HelpBActionPerformed

    private void LogoutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBActionPerformed
        int n = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Log Out Verification", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            this.dispose();
            new LauncherGUI().setVisible(true);
        }
    }//GEN-LAST:event_LogoutBActionPerformed

    private void MenuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBActionPerformed

        CardLayout card = (CardLayout) mainPanel1.getLayout();
        card.show(mainPanel1, "StartCard");
    }//GEN-LAST:event_MenuBActionPerformed

    private void MenuBMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBMouseDragged

        MenuB.setForeground(Color.YELLOW);
    }//GEN-LAST:event_MenuBMouseDragged

    private void MenuBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBMouseEntered

        MenuB.setForeground(Color.YELLOW);
    }//GEN-LAST:event_MenuBMouseEntered

    private void MenuBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBMouseExited

        MenuB.setForeground(Color.BLACK);
    }//GEN-LAST:event_MenuBMouseExited

    private void MenuFrmHighScoreBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFrmHighScoreBMouseClicked

    }//GEN-LAST:event_MenuFrmHighScoreBMouseClicked

    private void MenuFrmHighScoreBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFrmHighScoreBMouseEntered

        MenuFrmHighScoreB.setForeground(Color.YELLOW);
    }//GEN-LAST:event_MenuFrmHighScoreBMouseEntered

    private void MenuFrmHighScoreBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFrmHighScoreBMouseExited

        MenuFrmHighScoreB.setForeground(Color.BLACK);
    }//GEN-LAST:event_MenuFrmHighScoreBMouseExited

    private void MenuFrmHighScoreBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFrmHighScoreBActionPerformed

        CardLayout card = (CardLayout) mainPanel1.getLayout();
        card.show(mainPanel1, "StartCard");
    }//GEN-LAST:event_MenuFrmHighScoreBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);

            }
        });
    }

    public void setPlayingPlayer(Player player) {
        this.player = player;
        String cash = (!player.isBankrupt()) ? "$" + player.getCash() + "" : "BANKRUPT";
        WelcomeLabel.setText("Welcome, " + player.getUsername() + "!");
        CashLabel.setText(cash);
        if(player.isBankrupt()) {
            StartGameB.setEnabled(false);
        }
    }

    public void setHighScores() {
        HashMap<String, Player> players = IOHelper.deserialize();
        ArrayList<Player> playersByHighScore = new ArrayList<>(players.values());
        Collections.sort(playersByHighScore, Collections.reverseOrder(new Comparator<Player>() {
            @Override
            public int compare(Player p1, Player p2) {
                return Double.compare(p1.getCash(), p2.getCash());
            }
        }));
        int i = 1;
        for (Player p : playersByHighScore) {
            if (i == 1) {
                username1.setText(p.getUsername());
                score1.setText(p.getCash() + "");
            } else if (i == 2) {
                username2.setText(p.getUsername());
                score2.setText(p.getCash() + "");
            } else if (i == 3) {
                username3.setText(p.getUsername());
                score3.setText(p.getCash() + "");
            } else if (i == 4) {
                username4.setText(p.getUsername());
                score4.setText(p.getCash() + "");
            } else if (i == 5) {
                username5.setText(p.getUsername());
                score5.setText(p.getCash() + "");
            } else if (i == 6) {
                username6.setText(p.getUsername());
                score6.setText(p.getCash() + "");
            } else if (i == 7) {
                username7.setText(p.getUsername());
                score7.setText(p.getCash() + "");
            } else if (i == 8) {
                username8.setText(p.getUsername());
                score8.setText(p.getCash() + "");
            } else if (i == 9) {
                username9.setText(p.getUsername());
                score9.setText(p.getCash() + "");
            } else if (i == 10) {
                username10.setText(p.getUsername());
                score10.setText(p.getCash() + "");
            }
            i++;
        } // end for
    } // end function
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CashLabel;
    private javax.swing.JButton HelpB;
    private javax.swing.JPanel HelpPanel;
    private javax.swing.JPanel HighScorePanel;
    private javax.swing.JButton HighScoresB;
    private javax.swing.JButton LogoutB;
    private javax.swing.JButton MenuB;
    private javax.swing.JButton MenuFrmHighScoreB;
    private javax.swing.JLabel PokerTitle;
    private javax.swing.JButton StartGameB;
    private javax.swing.JPanel StartupPanel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel highscoreTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.pokergame.gui.MainPanel mainPanel1;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score10;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel score3;
    private javax.swing.JLabel score4;
    private javax.swing.JLabel score5;
    private javax.swing.JLabel score6;
    private javax.swing.JLabel score7;
    private javax.swing.JLabel score8;
    private javax.swing.JLabel score9;
    private javax.swing.JLabel scoreTitleLabel;
    private com.pokergame.gui.TablePanel tablePanel1;
    private com.pokergame.gui.TablePanel tablePanel2;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username10;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username4;
    private javax.swing.JLabel username5;
    private javax.swing.JLabel username6;
    private javax.swing.JLabel username7;
    private javax.swing.JLabel username8;
    private javax.swing.JLabel username9;
    private javax.swing.JLabel usernameTitleLabel;
    private com.pokergame.gui.WoodPanel woodPanel1;
    private com.pokergame.gui.WoodPanel woodPanel2;
    // End of variables declaration//GEN-END:variables
    private Player player;
}
